### ISSUE TITLE
Compilation Error in examples/multiple-callable-overrides.lang

### ISSUE THREAD

**Issue by DavidYeLuo** [PiJoules/lang#19]
# Summary
When trying to compile the program, we get compilation error in stdout.
```
9:15: Callable `writeln` with type `\IO int GENERIC -> IO` is handled by another callable
def writeln = \IO io int arg1 GENERIC arg2 -> IO
              ^
5:1: note: Declared here
def writeln = \IO io GENERIC arg1 GENERIC arg2 -> IO
^
```

## Issue
Looks like we are trying to overload a function with different param signature but our compiler can't handle it yet.

## Reproduction
Current Directory: ./lang/build
```
./bin/lang ../examples/multiple-callable-overrides.lang
```

**Comment by PiJoules** [comment]
There's a test in `tests/testparser.cpp` that's meant to test this specific error is triggered. See `MultipleCallableOverrides`. We want to ensure that we throw an error when there's multiple candidates for a function call.
